name        = "Loup"
name8       = "loup"
locale      = "fr"
variant     = "loup"
description = "French (Loué)"
author      = "fmairesse"
url         = "https://github.com/fmairesse/klayouts"
geometry    = "ERGO"
version     = "0.0.1"

# Optimized layout for french/english:
# - Qwerty/Azerty based:
#    - 15/30 keys moved from their initial position (21 for Colemak-DH, 23 for Ergol, 18 for Norman)
#    - 4 keys moved from left/right side or just 2 if omitting last transition
#    - Shortcuts preserved: ZXCVB cluster, Q, W, A, S unchanged
# - Intermediate Tarmak-like transitions:
#    - Qzerty-Lafayette with 1dk under thumb, ; → no key
#    - "ejkn."
#    - "loui" + duplicated "p" under [o]
#    - "pé"
#    - "jft"
#    - "rd"
# - Good finger load for right-handed (47%/53%) (55/45 for Ergol, 59/41 for Qwerty)
# - Good LSB (for column aligned keyboards): 2.61% VS 5.52% for Ergol
# - Not so good SFU but acceptable to me on a columnar keyboard: 3.27% VS 1.32% for Ergol
# - Rolls 17.7% inward and 13.5% VS 18.1%/15.5% for Ergol. Some good one:
#    - en, in, ien, ion, me, ke, kn


base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ ! „ │ @ “ │ # ” │ $ ¢ │ % ‰ ┃ ^   │ &   │ *   │ (   │ )   ┃ _   ┆ + ± ┆
┆ `   ┃ 1 ¡ │ 2 « │ 3 » │ 4 £ │ 5 € ┃ 6 ¥ │ 7 ¤ │ 8 § │ 9 ¶ │ 0 ° ┃ - — ┆ = ≠ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ W   │ F   │ D ™ │ J   ┃ Y   │ L   │ O   │ P   │ É   ┃     ┆ Z   ┆
·     ┃     │   é │   è │   « │   » ┃     │   ù │   ï │   œ │     ┃***¨ ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ S   │ R   │ T ª │ G   │ H   │ N   │ E   │ I   │ U   ┃ "   ┆ W   ┆
·     ┃   à │   ß │   ê │   ‑ │   – ┃   ñ │   û │   î │   ô │   ? ┃ '   ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ À   ┃ Z   │ X   │ C   │ V   │ B   │ :   │ M º │ ; • │ K   │ ? ÷ ┃           ·
┆     ┃   æ │   × │   ç │   _ │   — ┃ . … │  *µ │ , · │   … │ ! ¿ ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │   ≤ │   ≥ │   € │   ‰ ┃   ° │     │   × │  *´ │  *` ┃  *” ┆     ┆
·     ┃   ^ │   < │   > │   $ │   % ┃   @ │   & │   * │   ' │   ` ┃   " ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *ˇ │   ⁽ │   ⁾ │  *˙ │   ≠ ┃  */ │   ± │  *¯ │   ÷ │  *” ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   \ │   + │   - │   / │   " ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │  *, │  *˛ │   – │     ┃   ← │   → │   ⟹ │   ⟺ │  *˘ ┃           ·
┆     ┃   ~ │   [ │   ] │   _ │   # ┃   | │   ! │   ; │   : │   ? ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u00a0"  # NO-BREAK SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u2019"  # RIGHT SINGLE QUOTATION MARK
1dk_shift   = "\u2019"  # RIGHT SINGLE QUOTATION MARK
