name        = "Loup"
name8       = "loup"
locale      = "fr"
variant     = "loup"
description = "French (Loup)"
author      = "fmairesse"
url         = "https://github.com/fmairesse/klayouts"
geometry    = "ERGO"
version     = "0.0.1"

# asrt rather than arst because easier and does not make the stats worse on my corpus
# accept CR SFU: already used to it and dont want wo move C
# accept DR SFU: not a big deal and easy to learn
# L moved to the left for better finger load. It had to move far from its original position anyway.
# É instead of W because much more used in my corpus
# J would have been better for english in place of K, but "je" is so much more frequent than "kn|ke" in my corpus.
# P would theoretically be better in place of F. But this makes the moving of F more acceptable as
# we get "of" and "if" and avoids moving P
# 1dk to be used by thumb. Allows H on right pinky for easy "the"


base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ ! „ │ @ “ │ # ” │ $ ¢ │ % ‰ ┃ ^   │ &   │ *   │ (   │ )   ┃ _   ┆ + ± ┆
┆ `   ┃ 1 ¡ │ 2 « │ 3 » │ 4 £ │ 5 € ┃ 6 ¥ │ 7 ¤ │ 8 § │ 9 ¶ │ 0 ° ┃ - — ┆ = ≠ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ É   │ L   │ D ™ │ W   ┃ Y   │ F   │ O   │ U   │ H   ┃ {   ┆ }   ┆
·     ┃     │   æ │   ê │   « │   » ┃     │     │   œ │   ù │   û ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ R   │ A   │ S   │ T ª │ G   ┃ J   │ N   │ E   │ I   │ P   ┃ ? ¿ ┆ |   ┆
·     ┃   â │   à │   è │   ‑ │   – ┃   ñ │     │   ô │   ï │   î ┃***¨ ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ À   ┃ Z   │ X   │ C   │ V _ │ B — ┃ K   │ M º │ ; • │ :   │ ? ÷ ┃           ·
┆     ┃     │   × │   ç │   _ │   — ┃     │  *µ │ , · │ . … │ ! ¿ ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │   ≤ │   ≥ │   € │   ‰ ┃   ° │     │   × │  *´ │  *` ┃  *” ┆     ┆
·     ┃   ^ │   < │   > │   $ │   % ┃   @ │   & │   * │   ' │   ` ┃   " ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *ˇ │   ⁽ │   ⁾ │  *˙ │   ≠ ┃  */ │   ± │  *¯ │   ÷ │  *” ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   \ │   + │   - │   / │   " ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │  *, │  *˛ │   – │     ┃   ← │   → │   ⟹ │   ⟺ │  *˘ ┃           ·
┆     ┃   ~ │   [ │   ] │   _ │   # ┃   | │   ! │   ; │   : │   ? ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u00a0"  # NO-BREAK SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u2019"  # RIGHT SINGLE QUOTATION MARK
1dk_shift   = "\u2019"  # RIGHT SINGLE QUOTATION MARK
